baseURL = "https://wmhacoaching.com/"
languageCode = "en-us"
title = "WMHA Coaching"

# Enable HTML rendering on the website, e.g. iframe
[markup.goldmark.renderer]
unsafe = false

[[module.imports]]
path = "github.com/willfaught/paige"

[params.paige]
credit = "built with ❤️ by [nobe4](https://github.com/nobe4), with [hugo](https://gohugo.io/) and [paige](https://themes.gohugo.io/themes/paige/)"

[params.paige.list_page]
disable_authors = true
disable_collections = true
disable_date = true
disable_description = true
disable_keywords = true
disable_pages = true
disable_reading_time = true
disable_sections = true
disable_series = true
disable_summary = true
disable_title = true

[params.paige.page]
disable_alert = true
disable_authors = true
disable_date = true
disable_description = true
disable_edit = true
disable_history = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_title = true
disable_toc = true

[params.paige.site]
disable_reading_time = true
disable_breadcrumbs = true
disable_copyright = true
disable_description = true
disable_menu = true
disable_license = true
disable_credit = false
disable_title = false
